package com.example.testprojectgithub;

import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.DialogFragment;

import android.app.DatePickerDialog;
import android.app.Dialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;


import com.example.testprojectgithub.model.Game;
import com.example.testprojectgithub.model.SharedPrefManager;
import com.example.testprojectgithub.model.User;
import com.example.testprojectgithub.remote.ApiUtils;
import com.example.testprojectgithub.remote.GameService;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

public class NewGameActivity extends AppCompatActivity {

    private EditText txtName;
    private EditText txtDescription;
    private EditText txtRating;

    private static TextView tvReleaseDate; // static because need to be accessed by DatePickerFragment

    private static Date releaseDate; // static because need to be accessed by DatePickerFragment

    private Context context;

    /**
     * Date picker fragment class
     * Reference: https://developer.android.com/guide/topics/ui/controls/pickers
     */
    public static class DatePickerFragment extends DialogFragment
            implements DatePickerDialog.OnDateSetListener {

        @Override
        public Dialog onCreateDialog(Bundle savedInstanceState) {
            // Use the current date as the default date in the picker
            final Calendar c = Calendar.getInstance();
            int year = c.get(Calendar.YEAR);
            int month = c.get(Calendar.MONTH);
            int day = c.get(Calendar.DAY_OF_MONTH);

            // Create a new instance of DatePickerDialog and return it
            return new DatePickerDialog(getActivity(), this, year, month, day);
        }

        public void onDateSet(DatePicker view, int year, int month, int day) {
            // Do something with the date chosen by the user

            // create a date object from selected year, month and day
            releaseDate = new GregorianCalendar(year, month, day).getTime();

            // display in the label beside the button with specific date format
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            tvReleaseDate.setText( sdf.format(releaseDate) );
        }
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_new_game);

        // store context
        context = this;

        // get view objects references
        txtName = findViewById(R.id.txtName);
        txtDescription = findViewById(R.id.txtDescription);
        txtRating = findViewById(R.id.txtRating);
        tvReleaseDate = findViewById(R.id.tvReleaseDate);

        // set default createdAt value, get current date
        releaseDate = new Date();
        // display in the label beside the button with specific date format
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        tvReleaseDate.setText( sdf.format(releaseDate) );

    }

    /**
     * Called when pick date button is clicked. Display a date picker dialog
     * @param v
     */
    public void showDatePickerDialog(View v) {
        DialogFragment newFragment = new DatePickerFragment();
        newFragment.show(getSupportFragmentManager(), "datePicker");
    }

    /**
     * Called when Add Game button is clicked
     * @param v
     */
    public void addNewGame(View v) {
        // get values in form
        String gameName = txtName.getText().toString();
        String gameDescription = txtDescription.getText().toString();
        String gameRating = txtRating.getText().toString();

        // convert createdAt date to format in DB
        // reference: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String release_at = sdf.format(releaseDate);


        // create a Game object
        // set id to 0, it will be automatically generated by the db later
        // set image to dummy value
        Game g = new Game(0, gameName, gameDescription, gameRating, release_at);

        // get user info from SharedPreferences
        User user = SharedPrefManager.getInstance(getApplicationContext()).getUser();

        // send request to add new game to the REST API
        GameService gameService = ApiUtils.getGameService();
        Call<Game> call = gameService.addGame(user.getToken(), g);

        // execute
        call.enqueue(new Callback<Game>() {
            @Override
            public void onResponse(Call<Game> call, Response<Game> response) {

                // for debug purpose
                Log.d("MyApp:", "Response: " + response.raw().toString());

                // invalid session?
                if (response.code() == 401)
                    displayAlert("Invalid session. Please re-login");

                // game added successfully?
                Game addedGame = response.body();
                if (addedGame.getGameName() != null && addedGame.getGameRating() != null && addedGame.getGameDescription() != null) {
                    // display message
                    Toast.makeText(context,
                            addedGame.getGameName() + " added successfully.",
                            Toast.LENGTH_LONG).show();

                    // end this activity and forward user to GameListActivity
                    Intent intent = new Intent(context, GameListActivity.class);
                    startActivity(intent);
                    finish();
                } else  {
                    displayAlert("Add New Game failed.");
                }
            }

            @Override
            public void onFailure(Call<Game> call, Throwable t) {
                displayAlert("Error [" + t.getMessage() + "]");
                // for debug purpose
                Log.d("MyApp:", "Error: " + t.getCause().getMessage());
            }
        });
    }

    /**
     * Displaying an alert dialog with a single button
     * @param message - message to be displayed
     */
    public void displayAlert(String message) {
        AlertDialog.Builder builder = new AlertDialog.Builder(this);
        builder.setMessage(message)
                .setCancelable(false)
                .setPositiveButton("OK", new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int id) {
                        //do things
                        dialog.cancel();
                    }
                });
        AlertDialog alert = builder.create();
        alert.show();
    }
}
